version: '2'

services:

    # Web Server
    web:
        build:
            context: docker/development
            dockerfile: web.docker
        working_dir: /var/www
        volumes_from:
            - app
        ports:
            - "8080:80"
        links:
            - app

    # Web Application
    app:
        build:
            context: docker/development
            dockerfile: app.docker
        working_dir: /var/www
        volumes:
            - ./:/var/www/
        links:
            - db

    # Database
    db:
        build:
            context: docker/development
            dockerfile: db.docker
        ports:
            - 6379
